### ISSUE TITLE
Add suport to JSON fields

### ISSUE THREAD

**Issue by nicolashuber** [ArondeParon/laravel-request-sanitizer#1]
Is not possible handler JSON fields with dot notation, for exemple:

```
protected $sanitizers = [
        'cpf' => [
            RemoveNonNumeric::class,
        ],
        'store.cnpj' => [
            RemoveNonNumeric::class,
        ],
    ];
```

**Comment by ArondeParon** [comment]
Thanks for the feedback! I have pushed a [new release](https://github.com/ArondeParon/laravel-request-sanitizer/releases/tag/0.1.1) that implements support for dot notation.
