### ISSUE TITLE
Add sanitizers which cast to common data types

### ISSUE THREAD

**Issue by rimas-kudelis** [ArondeParon/laravel-request-sanitizer#2]
Basically, implement casting to bool, int, float, string (this would likely just do nothing), and maybe dates to Carbon instances?

**Comment by ArondeParon** [comment]
Great idea! 😄 Have you implemented these sanitizers in your own project already? If so, feel free to submit them in a pull-request and I will consider including them in the default sanitizers.

**Comment by francoism90** [comment]
@ArondeParon I would be interested in casting, however are these filters? I'm happy to make a PR for it. See examples given by Waavi: https://github.com/Waavi/Sanitizer/blob/master/src/Filters/Cast.php

**Comment by ArondeParon** [comment]
@francoism90 looks like an interesting solution! :) 

I could imagine doing something like this:

```php
protected $sanitizers = [
    'amount' => [
            Cast::class => [
                'to' => Cast::CAST_TYPE_FLOAT,
            ]
        ]
];
```

**Comment by francoism90** [comment]
@ArondeParon That looks cool! I'll take a look at your example and try to implement it. :)

**Comment by ArondeParon** [comment]
Good luck! You might be able to draw some inspiration from the [`FilterVars`](https://github.com/ArondeParon/laravel-request-sanitizer/blob/master/src/Sanitizers/FilterVars.php) implementation, which takes options as well.
