### ISSUE TITLE
Using custom filters alongside default filters on array properties

### ISSUE THREAD

**Issue by ZeroGodForce** [arondeparon/laravel-request-sanitizer#31]
I've written a custom filter based on `filter_var_array()` and inspired by the `FilterVars::class` to allow an array of repeating arrays (e.g. order lines) to be validated on a per-element level.  For example:

```php
<?php

namespace App\Filters;

use ArondeParon\RequestSanitizer\Contracts\Sanitizer;

class FilterRepeatingVarArray implements Sanitizer
{
    protected array $fields;

    public function __construct($fields = [])
    {
        $this->fields = $fields;
    }

    /**
     * Sanitize the nested array using the native PHP function: filter_var_array()
     * @param $input
     * @return array|null
     * @see https://www.php.net/manual/en/function.filter-var-array.php
     */
    public function sanitize($input): ?array
    {
        if (is_null($input)) {
            return $input;
        }

        $sanitized = [];
        foreach ($input as $item) {
            $sanitized[] = filter_var_array($item, $this->fields);
        }

        return $sanitized;
    }
}
```

Then in the form request it's defined like this:

```php
    protected array $sanitizers = [
        ...
        'order_line' => [
            FilterRepeatingVarArray::class => [
                'fields' => [
                    'quantity' => [
                        'filter' => FILTER_VALIDATE_INT,
                    ],
                    'price' => [
                        'filter' => FILTER_SANITIZE_NUMBER_FLOAT,
                        'flags' => FILTER_FLAG_ALLOW_FRACTION,
                        'options' => null,
                    ],
                ],
            ],
        ],
        ...
    ];
```

This appears to be working fine, but I'm not actually sure how I can apply any of the package's default filters to this kind of 2D array.  Ironically, it's brought me back to the original reason I wrote this custom filter; I'm not sure how (or if it's currently possible) to run filter classes on nested array elements?

Thanks for the library, it's ace!

**Comment by arondeparon** [comment]
Hi @ZeroGodForce, sorry for the absurdly late reply. I had not checked this library for a while and for some reason never spotted your comment.

> This appears to be working fine, but I'm not actually sure how I can apply any of the package's default filters to this kind of 2D array. 

I took a quick a look, and I don't think there is a way to dynamically achieve what you want to do right now; the library does support dot notation, but not wildcard notation, which would be needed here considering the potential variable number of array elements.

You could potentially manually call the sanitizers in your own sanitizer by dynamically passing them in the `$fields` property though 🤔
