### ISSUE TITLE
array_set() helper deprecated in Laravel 5.8

### ISSUE THREAD

**Issue by ammonkc** [ArondeParon/laravel-request-sanitizer#4]
Hi, I believe the `array_set()` helper method has been deprecated in Laravel 5.8. The concrete `Arr::set()` class should be used instead.

https://github.com/ArondeParon/laravel-request-sanitizer/blob/6909fe4e98d0cbb8167c66eefdcb01f6561ea579/src/Traits/SanitizesInputs.php#L35

**Comment by ArondeParon** [comment]
Hi @ammonkc, thank you for noticing! I have fixed this in the latest release.
